# Generated by Django 3.2.12 on 2025-10-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonusage',
            name='max_lessons',
            field=models.IntegerField(default=100),
        ),
    ]
