# Generated by Django 3.2.12 on 2025-11-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
