# Generated by Django 3.2.12 on 2025-11-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_grade_student_studentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='weight',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='grade',
            name='weight_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
